name: docs-guard
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi
      - name: Run Doc-Twin check
        env:
          BASE_REF: origin/${{ github.base_ref }}
          PR_LABELS: ${{ join(github.event.pull_request.labels.*.name, ',') }}
        run: node scripts/check-doc-twin.mjs
